import './globals.css'
import Navbar from '@/app/components/navbar'
import Footer from '@/app/components/socials'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <Navbar/>
      <body className='bg-cyan-500'>{children}</body>
      <Footer/>
    </html>
  )
}